//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_Analysis_Talking.Pro.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class news_subscribe
    {
        public int Id { get; set; }
        public string email_address { get; set; }
        public string nick_name { get; set; }
    }
}
