//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_Analysis_Talking.Pro.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Posts_()
        {
            this.authore = "Mr. Touraj Ostovari";
        }
    
        [System.ComponentModel.DataAnnotations.Schema.Column("IDS")]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string authore { get; set; }
        public string date { get; set; }
        public string image { get; set; }
        public string symbol { get; set; }
    }
}
