//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_Analysis_Talking.Pro.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users_()
        {
            this.username = "TourajOstovari";
            this.password = "123456";
        }
    
        public int Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string last_login_time { get; set; }
    }
}
